stan-dev/cmdstanpy

- .travis.yml
- cmdstanpy/io.py
- cmdstanpy/model.py
- cmdstanpy/tests.py
- dev/make_cmdstan.sh
- requirements.txt
- [x ] Run unit tests
I fixed the branch by maedoc.
I did some changes do travis works now.
This might not work on Windows 2.7.
> Travis fix

- .dockerignore
- cmdstanpy/model.py
- cmdstanpy/tests.py
- docs/Makefile
- docs/api.rst
- docs/conf.py
- docs/guide.rst
- docs/index.rst
- docs/make.bat
> Rm pycmdstan refs

- .gitignore
- cmdstanpy/cmdstan_args.py
- test/test_cmdstan_args.py
The `optimize` method doesn't have a concept of chains therefore I made it optional.
This is just the first phrase of integrating call to `optimize`.
- Salesforce
@mitzimorris
> Small change that will make chain_ids param optional (for optimize call)

- cmdstanpy/cmdstan_args.py
- cmdstanpy/model.py
- cmdstanpy/stanfit.py
- cmdstanpy/utils.py
- test/test_cmdstan_args.py
- test/test_model.py
- test/test_stanfit.py
Related issue: https://github.com/stan-dev/cmdstanpy/issues/60
Implemented call to `optimize` method. 
When optimizing all unrelated methods from `StanFit` will throw an exception. 
I am open for a discussion regarding methods' naming: `optimized_params_*`
- Salesforce
> Implemented Optimize support

- cmdstanpy/cmdstan_args.py
- cmdstanpy/model.py
- cmdstanpy/utils.py
- test/test_model.py
- test/test_utils.py
I've just realized I forgot to add support dict for `data` and `inits` parameters which is already supported by sampling method.
- Salesforce
> Added dict support for optimizing

- cmdstanpy/cmdstan_args.py
- cmdstanpy/model.py
- cmdstanpy/stanfit.py
- cmdstanpy/utils.py
- test/test_cmdstan_args.py
Minor fixes like exception type, more logging ad additional args check.
- Salesforce
> Minor fixes

- .appveyor.yml
- bin/install_cmdstan
- cmdstanpy/model.py
- cmdstanpy/stanfit.py
- cmdstanpy/utils.py
- test/test_cmdstan_args.py
- test/test_model.py
- test/test_stanfit.py
- test/test_utils.py
Add .appveyor.yml
Uses RTools
Updates tests to work on Windows.
> Add appveyor

- bin/install_cmdstan
- cmdstanpy/model.py
- cmdstanpy/stanfit.py
- cmdstanpy/utils.py
- test/test_cmdstan_args.py
- test/test_model.py
- test/test_utils.py
On Windows, if abspath contains spaces, use shortpath notation, which does not contain spaces.
> Windows short path

- cmdstanpy/model.py
Fixes  #93
Don't update `exe_file` if compilation is failed.
> Fix failed make

- README.md
> add docs to README

- docs/getting_started.rst
main change is fixing the model declaration: 
```
bernoulli_model = Model(
stan_file=os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan'),
exe_file=os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli')
)
```
the rest is insignificant.
> minor changes to getting started guide

- cmdstanpy/utils.py
> [WIP] update jsondump and rdump

- .appveyor.yml
- .travis.yml
> verbose pytest

- cmdstanpy/utils.py
> fix function name typo

- .travis.yml
- cmdstanpy/__init__.py
- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/model.py
- cmdstanpy/stanfit.py
Removes unused imports. Additionally has flake8 check for unused imports (except for those at the bottom of `__init__.py`.
> Remove unused imports

- .pylintrc
- .travis.yml
- requirements-test.txt
- test/example_script.py
- test/test_cmdstan_args.py
- test/test_cxx_installation.py
- test/test_generate_quantities.py
- test/test_model.py
- test/test_optimize.py
- test/test_runset.py
- test/test_sample.py
- test/test_utils.py
- test/test_variational.py
- ran pylint on all tests in dir `test`, fixed problems accordingly
- added pylint to travis workflow for dirs `cmdstanpy` and `test`
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University
> Feature/165 use pylint - add to travis.ci

- .appveyor.yml
Add codecov
Install rtools with cmdstanpy module
> Add codecov for appveyor

- cmdstanpy/model.py
Extra unwanted progress bars and empty lines were shown in the terminal during sampling, when running `sample` method with `show_progress=True` parameter. See examples of output below.
It looks like it's not a good idea to close progress bars while others are still updating. The glitch might be caused by tqdm's printing a new line on closure `fp_write('\n')`, the problem went away when I commented [this line in tqdm](https://github.com/tqdm/tqdm/blob/cc53d86f86cef63ba8dbbfb8e9cb27d4f247fd20/tqdm/std.py#L1269).
As a workaround, I've changed the code so that it closes the progress bars only after the sampling is completely finished (i.e. all chains and all threads are done).
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a …
> Remove unwanted progress bars

- cmdstanpy/__init__.py
- cmdstanpy/stanfit.py
- cmdstanpy/utils.py
- test/test_cmdstan_args.py
- test/test_utils.py
> Explicitly declare public API

- cmdstanpy/model.py
Change the chain_id rule from positive to non-negative
Change the rule for chain_id from positive to non-negative.
> chain_id rule to non-negative

- docs/installation.rst
There was a typo in the "Getting Started," so I changed that
> fix typo in installation.rst

- docs/variational_bayes.rst
> data name typo

- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/utils.py
- Fix a couple of bugs in the default compiler on Windows (RTools40).
- Install cxx compiler if not found in default location (only on Windows with a special argument `-c`, `--compiler`)
> Update and refine windows tools

- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/stanfit.py
- test/test_runset.py
- test/test_sample.py
> add more tests

- cmdstanpy/model.py
> Fixed typo in model.py

- Jenkinsfile
- rtd_change_default_version.py
- [ x ] Declare copyright holder and open-source license: see below
PR that handles issue #295 of release and documentation.
We're automating this process through a Jenkins job, note that readthedocs call to change the default version is done through python requests and session rather than an API request ( they do not have one for the default version ).
The process is:
- Create a new branch for the release, release/v1.0.0 for example
- Update version in cmdstanpy/_version.py
- Generate docs in docsrc with make github
- Push the new branch to upstream
- Merge new branch into develop
- Create a new tag with the release version
- Update master branch to the new version
- Install, build and push to pypi
- Change default version in readthedocs.
Please list the copyright holder for the work you …
> Package release

- test/test_sample.py
Fixes #298 (`test_multi_proc` is too brittle). The "number of cores" logic in the test needed to match the logic in the source code.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Imad Ali
> Fixing test_multi_proc

- cmdstanpy/stanfit.py
stray code was added to feature/300 branch but not needed after all - cleanup
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):   Columbia University
> code cleanup

- .appveyor.yml
- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/utils.py
Add progress bar for download
Update Windows cxx logic and default folders
> Update install_cmdstan and install_cxx_toolchain

- .appveyor.yml
- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
I tested this locally and this works. I think there is some error with `subprocess.poll` if stdout has too much of data.
> empty stdout buffer

- cmdstanpy/utils.py
- test/test_cmdstan_args.py
- test/test_sample.py
- test/test_utils.py
I don't know a good way to test multiple cmdstan versions without installing multiple versions.
Also changed a bunch of tests to use tempfolder.
> fix test_utils tests

- .gitignore
- docsrc/sample.rst
I noticed that some of the parameters in the sampling rst page were duplicated due to being at
the same time in the hmc-nuts specific section and at the common params file. In addition, some
other parameters present in the api docs were missing. And lastly, I added a link to the
`CmdStanModel.sample` api section to ease navigation. Let me know what you think.
> Minor doc fixes

- .pylintrc
- cmdstanpy/__init__.py
- cmdstanpy/utils.py
- test/test_utils.py
Add option to extract ndim objects.
> Add extract function

- cmdstanpy/stanfit.py
- test/data/container_vars.stan
- test/test_sample.py
> use explicit Fortran order for reshaping.

- cmdstanpy/cmdstan_args.py
- cmdstanpy_tutorial.py
- test/test_sample.py
> fix lint and black

- cmdstanpy/utils.py
- test/test_utils.py
e.g. pandas or other numpy wrappers
See #397 
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Brian Ward, Flatiron Institute
> Support json dumping for more collections

- .flake8
- .pre-commit-config.yaml
- .pylintrc
- CONTRIBUTING.md
- test/test_generate_quantities.py
- test/test_metadata.py
- test/test_sample.py
This PR adds the necessary configurations to allow the use of [pre-commit](https://pre-commit.com/) to automatically run all of our code linting and formatting when a commit is made. Anyone interested in using this should install pre-commit and then run `pre-commit install` in their local copy of the repository. 
As part of this I've moved our standard flake8 settings to a .flake8 file. If we want, we can use this in the github action to keep the settings all in one place.
Additionally, I've duplicated the developer information in the wiki into CONTRIBUTING.md. I think this will make it easier for new developers to orient themselves, as the wiki is not always the first place I would check for this kind of information.
By submitting this pull request, the copyright holder is agreeing to …
> Bookkeeping

- cmdstanpy/install_cmdstan.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/utils.py
While working on #412, I noticed that these methods were identical in `install_cmdstan` and `install_cxx_toolchain`. 
This PR simply moves them to utils.
> Refactor install scripts to remove redudancy

- cmdstanpy/compiler_opts.py
- test/test_compiler_opts.py
Resolves #261 and #394. As discussed in those issues, this allows arbitrary make arguments to be passed, while still handling the existing checks on the OPENCL arguments.
> Remove cpp option whitelist

- docsrc/_templates/layout.html
- docsrc/conf.py
Follow on to #435, this increases depth of the table of contents (right sidebar) and darkens the top bar to match cmdstanr's and provide a stronger contrast.
> Polish doc appearance

- .github/workflows/release.yml
This PR adds the new doc dependencies to the github action
> Update release action for new docs

- .github/workflows/release.yml
I think this resolves the second error I'm now getting
> Add iPyKernel to doc build

- docsrc/Makefile
> Remove contents of docs before we recursively copy newly build docs

- docsrc/Makefile
- docsrc/conf.py
> Revert removing _modules dir from docs/

- README.md
- cmdstanpy_tutorial.ipynb
- cmdstanpy_tutorial.py
- docsrc/examples/MCMC Sampling.ipynb
- docsrc/examples/Maximum Likelihood Estimation.ipynb
- docsrc/examples/Run Generated Quantities.ipynb
- docsrc/examples/Variational Inference.ipynb
- docsrc/hello_world.rst
Resolves #446
Updates readme and documentation to prefer generic names like 'fit' and 'model'. Closes #446 
> Prefer generic names in examples

- cmdstanpy/stanfit.py
- docsrc/conf.py
- test/data/shape.stan
- test/test_optimize.py
- test/test_variational.py
> fix shaping issues

- cmdstanpy/utils.py
- test/__init__.py
- test/test_generate_quantities.py
- test/test_sample.py
- test/test_utils.py
Closes #485
Mentions disk space as a possible cause for the rror
> Give more informative error for bad draws (highlight disk space as possible culprit)

- .github/workflows/main.yml
Closes #465 
Test CmdStanPy on Python 3.10
> Test Python 3.10

- cmdstanpy/__init__.py
- cmdstanpy/install_cxx_toolchain.py
- cmdstanpy/utils.py
- docsrc/api.rst
- docsrc/conf.py
- docsrc/env.yml
- docsrc/internal_api.rst
- test/test_runset.py
Adds an internal API documentation page for items we don't want users to rely on/assume they are stable.
Simon's Foundation
> Document some API features as 'internal'

- cmdstanpy/install_cmdstan.py
Closes #514 with the improved message suggested here: https://github.com/stan-dev/cmdstanpy/issues/514#issuecomment-1014845420
> Update message if version cannot be found

- cmdstanpy/compiler_opts.py
- cmdstanpy/model.py
This is a follow on to #518. It closes #520 and makes `src_info` also respect the allow-undefined or other flags. `--info` will safely ignore flags like `--use-opencl`.
> Compose stanc args separately from C++

- .github/workflows/main.yml
Install the requested version 
Simons foundation
> Specify version to install in GHA

- cmdstanpy/compiler_opts.py
- test/test_compiler_opts.py
> Added passing of new stanc O options as well as validation

- cmdstanpy/cmdstan_args.py
- cmdstanpy/utils.py
- test/test_cxx_installation.py
- test/test_generate_quantities.py
- test/test_optimize.py
- test/test_sample.py
- test/test_utils.py
- test/test_variational.py
Our tests had a some inconsistent patterns (like `assertTrue(x in y)` rather than `assertIn(x, y)`). This cleans those up. We may also want to consider more test refactors like those discussed here: https://github.com/stan-dev/cmdstanpy/pull/530#discussion_r796114057
> Tidy up tests

- .github/workflows/main.yml
- .github/workflows/release.yml
pip needs a `python -m pip` structure to update itself.
> Fix pip upgrade issue

- .pylintrc
- cmdstanpy/model.py
- cmdstanpy/utils.py
- test/__init__.py
- test/test_compiler_opts.py
- test/test_generate_quantities.py
- test/test_model.py
- test/test_optimize.py
- test/test_runset.py
- test/test_sample.py
- test/test_variational.py
This code was triggered when running `cmdstan_path`
> Remove debug print statement

- docsrc/installation.rst
os was not imported that code snippet won't work without it
> missing import in Quickstart to installation

- MANIFEST.in
- cmdstanpy/cmdstan_args.py
- cmdstanpy/compiler_opts.py
- cmdstanpy/model.py
- cmdstanpy/utils.py
- setup.py
This closes #572. The only changes are type-annotation related
> Add py.typed and accept os.PathLike objects for paths

- docsrc/installation.rst
> Document --interactive argument

- cmdstanpy/utils.py
Fix typo in `show_versions()`: `tdqm` -> `tqdm`
> Fix typo in show_versions(): tdqm -> tqdm

- docsrc/community.rst
Add a link to https://github.com/WardBrian/cookiecutter-cmdstanpy-wrapper to the Community section
> Add cookiecutter-cmdstanpy-wrapper to community docs

- cmdstanpy/stanfit/gq.py
- cmdstanpy/stanfit/mcmc.py
- test/test_generate_quantities.py
- test/test_sample.py
Replace `set(vars_list)` with `dict.fromkeys(vars_list)`.
> Keep column order for dataframe

- cmdstanpy/__init__.py
> removed logging in atexit handler #603

- test/conftest.py
Follow on to #604, #605. We added this code in #530 to work around a pytest bug with logging, but it is no longer necessary.
> Remove extra test setup code

- docsrc/changes.rst
- docsrc/conf.py
Update release notes for 1.0.5 (#607)
> Update release notes

- docsrc/changes.rst
Closes #625. I will run a release whenever this gets approved/merged @mitzimorris @ahartikainen 
Simons Foundation.
> Add changelog for 1.0.8

- .github/dependabot.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
Recent runs have raised a lot of warnings, see: https://github.com/stan-dev/cmdstanpy/actions/runs/3420365827
This updates the versions and opts-in to dependabot to automatically check for these updates going forward.
> Update GHA workflows to remove deprecated features

- docsrc/community.rst
Adds [BridgeStan](https://github.com/roualdes/bridgestan) to the community page of the documentation
> Add BridgeStan to the community page

- cmdstanpy/model.py
- test/test_compiler_opts.py
- test/test_cxx_installation.py
- test/test_generate_quantities.py
- test/test_install_cmdstan.py
- test/test_model.py
- test/test_utils.py
Adds a minimum version check to the new functionality added in #634 
>  Add version bounds on standalone GQ for non-HMC 

- cmdstanpy/cmdstan_args.py
- test/test_cmdstan_args.py
Closes #647. For our argument validation, we don't really care about the differences between `int` and `np.int32` and friends, since we serialize to a string anyway.
> Accept np.floating and np.integer for arguments

- cmdstanpy/model.py
- test/test_log_prob.py
This PR fixes a broken test due to changes in cmdstan (see [here](https://github.com/stan-dev/cmdstan/commit/3f0e619e9328db5acaabec3226932336be3beb2b#diff-13993f3e62b780f5eb82ce68865633df636c2de0eac804de9529c602fe98406eL558-R559)).
> Fix `lp__` test.

- docsrc/users-guide/examples/Using External C++.ipynb
- docsrc/users-guide/examples/make_odds.hpp
Closes #666. This includes essentially the same changes as https://github.com/stan-dev/docs/pull/626
> Update documentation on external C++

- .github/workflows/main.yml
- cmdstanpy/stanfit/mcmc.py
- docsrc/users-guide/examples/MCMC Sampling.ipynb
> Update wording on `diagnose()` suggestion

- cmdstanpy/install_cmdstan.py
Always run `compile_example` as discussed in #703.
> Always run `compile_example` in `install_cmdstan` (fixes #703).

- .github/workflows/main.yml
- cmdstanpy/compilation.py
- cmdstanpy/compiler_opts.py
- cmdstanpy/model.py
- cmdstanpy/stanfit/gq.py
- cmdstanpy/stanfit/mle.py
- cmdstanpy/stanfit/vb.py
- docsrc/changes.rst
- docsrc/users-guide/examples/VI as Sampler Inits.ipynb
- test/test_generate_quantities.py
- test/test_optimize.py
- test/test_variational.py
See #690. This is PR is assuming we go down the "issue as many warnings as possible for a version" branch before releasing a 2.0
> Prep for release v1.2.0

- cmdstanpy/cmdstan_args.py
- cmdstanpy/model.py
Came up in #711, this may be required in numpy 2.0
> Switch from np.random.RandomState to default_rng

- cmdstanpy/cmdstan_args.py
- cmdstanpy/model.py
- cmdstanpy/stanfit/pathfinder.py
- test/test_log_prob.py
- test/test_pathfinder.py
Closes #726. Adds the new arguments from https://github.com/stan-dev/cmdstan/pull/1234
> Add new Pathfinder arguments

- docsrc/changes.rst
We should do a minor release for cmdstan 2.35 compatibility. 
> Update changes.rst for patch 1.2.3

- .github/workflows/main.yml
- docsrc/api.rst
> Add rebuild_cmdstan to API doc

- docsrc/changes.rst
Updates release notes so we can release 1.2.5 alongside cmdstan 2.36
> Update changes.rst for 1.2.5 patch
