cmdstanpy/cmds.py
test/data/bernoulli_include.stan
test/data/divide_real_by_two.stan
test/test_cmds.py

This change allows a user to specify one or more include paths using the method introduced [here](https://github.com/stan-dev/stan/pull/2635) when calling the `compile_model` function using the following syntax:
```
model = compile_model(stan_file, include_paths=['path/to/directory'])
```
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Technical University of Denmark

Allow user to specify include path for stan files

---

README.md
bin/install_cmdstan
cmdstanpy/__init__.py
cmdstanpy/cmds.py
cmdstanpy/lib.py
cmdstanpy/utils.py
pyproject.toml
setup.py
test/test_cmds.py
test/test_model.py
test/test_runset.py
test/test_sampler_args.py
test/test_utils.py

Created `EXTENSION` constant that is `".exe"` on Windows and otherwise `""`
Added `Path(path).as_posix()` in some places.
There was bug in repr (`self.args` --> `self._args`)

fix windows behaviour

---

cmdstanpy/model.py
test/test_model.py

In some cases user might want to use `cmdstanpy` without the source and using only the compiled executable. 
A good example might be Prophet library where compilation should be done during the installation phrase.
- Salesforce

Allow to instantiate Model without Stan source

---

cmdstanpy/model.py
cmdstanpy/utils.py
test/test_model.py
test/test_utils.py

According to this issue: https://github.com/stan-dev/cmdstanpy/issues/17
when the source file is in path that contains spaces (e.g. the model file itself can be named that way) the `make` command will fail. 
In order to mitigate this we will copy the source file to a temporary location, compile it, and then copy back generated model to the original directory.
There is still a possibility where the generated temporary path might contain spaces (e.g. under Windows) and we will simply throw an exception.
- Salesforce
- Code: BSD …

Fix spaces problem in source path

---

setup.py
test/test_model.py

A couple of changes to fix errors I got when trying to pip install the latest cmdstanpy.
The first error happened when I tried to install from github, but it also happens when I try `pip install -e .` in a fresh virtual environment:
```
(venv) ~/Code/cloned/cmdstanpy master $ pip install -e .
Obtaining file:///Users/tedgro/Code/cloned/cmdstanpy
Installing build dependencies ... done
Getting requirements to build wheel ... error
ERROR: Complete output from command /Users/tedgro/Code/cloned/cmdstanpy/venv/bin/python3.7 /Users/tedgro/Code/cloned/cmdstanpy/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/nw/nbg0t9fx0hvdhwlgwk2kb48wqkndw3/T/tmphio8017a:
ERROR: deleting tmpfiles dir: …
```

Fix setup.py import bug, ensure pandas has to_numpy method

---

cmdstanpy/model.py

Instead of having number of cores set to 1 by default, let's set it to the number of chains with the limitation of `cpu_count - 2` (to leave some cores for the OS).
- Salesforce

Automatically set number of used cores

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py
test/test_model.py
test/test_stanfit.py

- Replaced `print` calls with `logger.[...]`
- `diagnose` will return string directly if problems found, otherwise `None`
Related issue: https://github.com/stan-dev/cmdstanpy/issues/74
- Salesforce

Use logging module instead of print

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py
test/test_cmdstan_args.py
test/test_model.py
test/test_stanfit.py
test/test_utils.py

Call `os.makedirs(dir, exist_ok=True)` in try-except block to have a possibility to create csv-files in a new dir. 
If this fail, then it will raise OSError and it is handled correctly.

makedirs while testing if file can be written

---

.travis.yml
bin/install_cmdstan

Github connection fails from time to time. `travis_retry` tries to run the command 3 times before failure.

Use cache and retry for url download in .travis.yml

---

cmdstanpy/model.py

Change `multiprocessing.ThreadPool` to `concurrent.futures.ThreadPoolExecutor`
Currently nothing changes, but it is a newer library and gives us opportunity to handle more with each thread.
https://docs.python.org/3/library/concurrent.futures.html

Use concurrent.futures.ThreadPoolExecutor

---

cmdstanpy_tutorial.ipynb

Minor correction in `cmdstanpy_tutorial.ipynb` to have `bern_json` be an existing json file. (On master `bern_json` was equal to `examples/bernoulli/bernoulli.stan/bernoulli.data.json`)
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Thomas J Fan

[MRG] DOC Uses correct path to data.json in cmdstanpy_tutorial.ipynb

---

cmdstanpy/model.py

concurrent futures should work but doesn't - needs investigation.
reverting to using ThreadPool.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

reverting to ThreadPool, not using concurrent futures

---

cmdstanpy/__init__.py
cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy_tutorial.ipynb
docs/api.rst
docs/getting_started.rst
test/test_generate_quantities.py
test/test_optimize.py
test/test_runset.py
test/test_sample.py
test/test_variational.py

Changed name of class `StanFit` to `StanMCMC` in code, docs, and ipython notebooks.
Added `__repr__` function to classes `StanMCMC`, `StanMLE`, `StanQuantities`, and `StanVariational`.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

changed class StanFit to StanMCMC, added __repr__ methods

---

cmdstanpy/model.py

Fixes #142 
Minimal change, define w_iters if warmup_iters is defined.

Define w_iters if warmup_iters is defined

---

.appveyor.yml
.travis.yml
cmdstanpy/cmdstan_args.py
cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py
scripts/clean_examples.py

Add libTBB to $PATH on Windows and fix the env variable handling for subprocess.
Changes the default `make` to `mingw32-make` on Windows.

Enable TBB on Windows

---

cmdstanpy/model.py
test/test_model.py

Replace usage of `bin/stanc` with `make`. Fixes #169.

Compile with make instead of bin/stanc

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
test/data/bernoulli with space in name.stan
test/data/path with space/bernoulli_path_with_space.stan
test/test_cmdstan_args.py
test/test_sample.py

Changes command into a List. Previously it was a String and `.split()` was used. In addition an absolute path is used for the target stanfile in the scenario where it is copied from a tmpdir.
Fixes #167 and fixes #91.

Implement cmd as List

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/utils.py
test/test_sample.py

Bugfix - sampler arg `inits` should allow scalar int or float, but this was overlooked when implementing util methods to deal with the case where it is a pathname.  Cleaned up the logic, added unit tests.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

cleanup utils logic, add unit tests

---

test/test_model.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

Cleans up test data after tests are run. Fixes #174.
Alternatively a temporary directory could be used to store the files instead of this PR.

Cleanup tests

---

docs/generate_quantities.rst
docs/optimize.rst
docs/sample.rst
docs/variational_bayes.rst

Use code:: instead of code-block::
code-block:: not rendering on readthedocs
Change ipython3 blocks to python
ipython3 code blocks don't show up in Sphinx documentation, but
python blocks do
Fixes #178.
This should fix the rendering of some code blocks on readthedocs. I'm unable to test other than locally, where it isn't a problem like it is online.

Fix non-rendering code blocks

---

.travis.yml
test/example_script.py
test/test_cmdstan_args.py
test/test_cxx_installation.py
test/test_generate_quantities.py
test/test_model.py
test/test_optimize.py
test/test_sample.py
test/test_utils.py
test/test_variational.py

Adds `flake8` for the test dir in Travis. Updates style in test files in order to pass `flake8`.

Add flake8 for test dir

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
docs/common_config.rst

Adds an option to `sampler`, 'optimize', and 'variational' methods for outputting diagnostic files.
Fixes #158.

Implementation of save_diagnostics for sampler

---

cmdstanpy/model.py
test/test_model.py

It was not easy to read the error messages for .stan file with syntax errors. The error messages were all printed out in one line because the new line characters were escaped. I've changed it so the new lines are shown as new lines, so the errors are now more readable. :) See #193.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Me
Yes, agree

Make Stan model syntax errors readable

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
requirements-test.txt
test/test_model.py

* Use a single progress bar instead of separate bars for warmup and sampling. This simplifies code since cmdstan output also combines warmup and sampling.
* Change the description of the bar from "warmup", to "sample" to "done" to indicate the stage of sampling.
* For Jupyter only, make each bar green as soon as it's done.
* I've deleted a lot of progress bar code following comment "read and process rest of the stdout if needed", I could not figure out what it was for, and everything worked for me without it.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): me
- Code: BSD 3-clause …

Use single progress bar

---

cmdstanpy/cmdstan_args.py
test/test_model.py

I got an error when trying to use the 'dense' metric option. This code should reproduce the error: 
```
import cmdstanpy
import os
bernoulli_stan = os.path.join(
cmdstanpy.cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan'
)
bernoulli_model = cmdstanpy.CmdStanModel(stan_file=bernoulli_stan)
bernoulli_data = { "N" : 10, "y" : [0,1,0,0,0,0,0,0,0,1] }
bern_fit = bernoulli_model.sample(
data=bernoulli_data, output_dir='.', metric='dense'
)
```
From the output `.txt` files it looks like the problem is that the `metric_file` isn't being set correctly, which I think happens because of a clash in `cmdstan_args` between `dims = []` at line 127 and `if dims is not None` at line 173. 
This change makes those two statements agree and fixed the error on my computer.
I've also bundled an …

Bug: fix the `metric` option

---

cmdstanpy/cmdstan_args.py
test/test_sample.py

cmdstan interprets the quotes as parts of the filename, causing it to fail to find the files.
Google Inc.

Don't quote metric files.

---

cmdstanpy/utils.py
test/test_utils.py

`utils.jsondump` alters the users dictionary... turning numpy arrays into lists.
This pull request ensures that the users input data dict remains the same after calling
say `sample`.
It's a surpise to find you code failing after calling sample... and then finding
all your numpy arrays are now simple lists.
Also... I ran the tests  with cmdstan 2.22.1 and your `test_model_syntax_error` failed.
Don't know what you what to do with that...
Most of the changes are in the test which also assumes this change has occured.
Copyright is yours now...
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following …

don't alter users data dict

---

cmdstanpy/model.py
cmdstanpy/stanfit.py
test/test_sample.py

Added argument to CmdStanMCMC `summary` method allowing user to specify percentiles to report.
Added unit tests, while doing, made `diagnose` unit test a little less brittle.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

added percentiles arg to summary command, unit tests

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py

Raise child exception using `from exc` syntax.

raise exception from parent exception

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/utils.py
test/test_cmdstan_args.py
test/test_variational.py

Hi! I was exploring the possibility of migrating a project from pystan to cmdstanpy in order to access a more up-to-date version of stanc via a python interface. During that exploration, I found that there was some unexpected behavior when working with the variational interface. I poked around in the codebase and found a few problems that I attempted to fix in this PR. In particular:
- Some of the `Real` parameters in `VariationalArgs` were being constrained to be `>=1` rather than `>0`, which resulted in unexpected validation errors when I supplied values less than 1, e.g. `eta = 0.1`, or `tol_rel_obj = 0.05`.
- The interface did not support disabling eta adaptation, which is supported by cmdstan, and is supported by other stan interfaces.
- When disabling eta adaptation, the output file …

Some fixes/additions to the variational arguments

---

.gitignore
cmdstanpy/stanfit.py
cmdstanpy/utils.py
rtd_change_default_version.py
test/test_generate_quantities.py
test/test_sample.py

This PR fixes the bug which caused per chain options to fail.
Now user can set these values individually per chain: `stepsize`, `inits`, `metric_file`, `seed`.

Enable per chain options

---

cmdstanpy/utils.py

Reuse of variable `i` inside `MaybeDictToFilePath` causing error when list of strings used to initialise parameters on line 1009. Fixed by renaming to `j`.
I am the copyright holder of this submission and agree to license it under BSD 3-clause

IndexError bugfix for per-chain initialisation

---

cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/model.py
cmdstanpy/utils.py

We don't use stdin so we can use `subprocess.DEVNULL`. This enables CmdStanPy to execute on a RStudio (and similar) environments.

define empty stdin for Popen calls

---

.github/workflows/main.yml
.github/workflows/release.yml

This PR will move the release process from a [Jenkins Job](https://github.com/stan-dev/cmdstanpy/blob/develop/Jenkinsfile) to Github Actions.
It's a workflow triggered manually, with two parameters:
* new_version - New version to release, for example: 0.9.68
When triggered it will do the following:
- Create a release branch out of develop
- Update version in `cmdstanpy/_version.py`
- Generate docs
- Push branch
- Merge release branch into develop
- Create a tag out of develop
- Update master to new version
- Build wheels
- Install Wheels
- Upload to pypi
- Update default version in `readthedocs` to the new version released
Note!!! The [main](https://github.com/stan-dev/cmdstanpy/blob/develop/.github/workflows/main.yml) workflow is not pushing the package to pypi anymore, it will just run …

[WIP] Move release from Jenkins to Github Actions

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
test/test_cmdstan_args.py

This change allows the user to set the `CmdStanArgs` argument `refresh` by adding a matching argument to the method `CmdStanModel.sample`. 
The main reason for doing this is to control the tqdm progress bar's granularity: for example setting `refresh` to 1 makes the progress bar update every iteration. Someone also might want to do this in order to tell from the `stdout.txt` file exactly at what iteration a message was printed.
Teddy Groves

Add refresh argument to CmdStanModel.sample

---

cmdstanpy/utils.py
test/test_sample.py
test/test_utils.py

JSON serialization currently falls down if the `data` dictionary values include numpy scalars (with `TypeError: $SCALAR is not JSON serializable`). Fix type-check to catch these, in addition to arrays (the `tolist()` conversion still works as expected to convert to builtin `int`/`float`).
I am the copyright holder of this work and agree to the terms of the license.

broaden type check to include numpy scalars (in addition to `ndarray`)

---

cmdstanpy/cmdstan_args.py
test/data/optimize/no_data.stan
test/test_optimize.py

Fixes #348 with @nourfahmy 
It's now okay to run the optimize function with no data supplied (so the behavior is the same as with sampling now)
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

Allow optimize to have no data (Issue #348)

---

cmdstanpy_tutorial.ipynb
cmdstanpy_tutorial.py

The `stepsize` attribute does not exist on `CmdStanMCMC`. Apparently it should be `step_size` instead.
Myself (Ben Mares)

Fix stepsize → step_size

---

cmdstanpy/model.py
cmdstanpy/stanfit.py
test/test_model.py
test/test_sample.py

Fixes #377 
This fixes the issue with recompilation caused by the temp-folder hack used for the paths with spaces.
Check first if exe file exists in the original folder, then check against possible temp file.

Fix space in path issue for checking exe file

---

.gitignore
cmdstanpy/stanfit.py
requirements-optional.txt
requirements-test.txt
test/data/.gitignore
test/data/bernoulli_array.stan
test/test_model.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

Add an optional dependency on [xarray](https://xarray.pydata.org/en/stable/index.html) and add the ability to call `.draws_xr()` on a CmdStanMCMC object. Modeled after `.draws_pd()`
This allows more natural processing of multi-dimensional quantities, and should interop slightly easier with packages like arviz which use xarray extensively. 

Support xarray draws object

---

cmdstanpy/__init__.py
cmdstanpy/cmdstan_args.py
cmdstanpy/compiler_opts.py
cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py
cmdstanpy_tutorial.py
docsrc/conf.py
pyproject.toml
test/test_compiler_opts.py
test/test_optimize.py
test/test_utils.py

This PR mainly makes changes to the optional typing to bring them up to the standards used by mypy and other linters, as discussed here https://github.com/stan-dev/cmdstanpy/pull/408#discussion_r670471957. Any example of this is turning something like 
`dims: list = None`
into
`dims: Optional[List[int]] = None`
The package now very nearly passes `mypy --strict`, with all of the remaining errors being benign. Fixing them requires using `numpy.typing`, which isn't available to us until we make the numpy minimum version 1.21.
Some minor semantic changes were made to make the types clearer. These should have no outward-facing impact, and all existing tests still pass. This mainly included changing the default values of some variables to match their eventual types, and changing calls like …

Typing fixes

---

cmdstanpy/install_cmdstan.py
cmdstanpy/utils.py

This PR does five things, all related to open problems with the installation script/function:
* Resolves #351
Output is now 
```python
>>> import cmdstanpy
>>> cmdstanpy.install_cmdstan(verbose=True)
Installing CmdStan version: 2.27.0
Install directory: /home/brian/.cmdstan
Downloading CmdStan version 2.27.0
Download successful, file: /tmp/tmpf5fuwyke
Unpacked download as cmdstan-2.27.0
...[installation continues]
True
```
* Resolves #275
Output is now
```python
>>> import cmdstanpy
>>> cmdstanpy.install_cmdstan(dir='/home/brian/.cmdstancustom')
Installing CmdStan version: 2.27.0
Install directory: /home/brian/.cmdstancustom
... [installation continues]
True
>>> cmdstanpy.cmdstan_path()
'/home/brian/.cmdstancustom/cmdstan-2.27.0'
```
* Resolves #396 
The install script now checks that …

Resolve several issues related to install functionality

---

cmdstanpy/__init__.py
cmdstanpy/model.py
cmdstanpy/utils.py
test/test_utils.py

Addresses #410 by exposing `jsondump` as `write_stan_json` and **removing** `rdump`. 
As part of this I am allowing the more general `Mapping` type (which essentially means `.items()` is implemented) rather than strictly `Dict`, so you can now do things like `write_stan_json(path, dataframe)` or even `write_stan_json(path, xarray_dataset)`
I also added additional checks modeled on the cmdstanr function of the same name for clarity. These checks consist of:
* Verify the type of each value is numeric, a boolean, or a collection with a meaningful error if not.
* Verify that the values present are finite (meaning not NaN or inf/-inf)
Checking these two issues in particular mean that the call to `ujson.dump` should never itself fail
Please list the copyright holder for the work you are …

Expose write_stan_json utility

---

.github/workflows/main.yml
.pre-commit-config.yaml
cmdstanpy/cmdstan_args.py
cmdstanpy/compiler_opts.py
cmdstanpy/model.py
cmdstanpy/stanfit.py
cmdstanpy/utils.py
pyproject.toml
requirements-test.txt
test/test_generate_quantities.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

* Finishes #415. Uses `get_logger` universally, caches `get_logger`, and emits deprecation warnings if old keyword is used, to be removed in 1.0
* Fixes some typos that made it through review ('depreciated' vs 'deprecated')
* Fix some mypy errors **and add mypy to the CI**. This may be controversial, as it will end up rejecting a lot of first passes, but if we'd like to commit to having a decently typed package, that needs to be enforced automatically somewhere.
* Add tests that mock xarray not being installed to ensure correct behavior of `.draws_xr` in that case 
By submitting this pull request, the copyright holder is agreeing to …

Code cleanup - mypy enforcement and typo correction

---

cmdstanpy/model.py

Resolves #382. Based on the same idea in cmdstanr
This is a (partial?) solution to #382. It produces a warning if the compile command fails for this reason, which currently directs the user to call `install_cmdstan(overwrite=True)`. 
If we believe there is merit to providing a separate `rebuild_cmdstan()`, I can refactor the install code to support this, but it would be largely the same as this call, I believe. 
I should also mention I'm not sure how to artificially recreate this issue to test it, but the logic behind showing the warning is simple enough (based on cmdstanr) that I am pretty positive it would work
By submitting this pull …

Add warnings for PCH error

---

cmdstanpy/model.py
test/test_variational.py

Resolves #347 as discussed in that issue

Change require_converged behavior

---

cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/utils.py

The logic for finding a cmdstan instance is complicated by the legacy support for `~/.cmdstanpy`. This PR emits a warning whenever this is detected asking the user to rename to the newer `~/.cmdstan`, so we can drop this for version 1.0

Formally mark ~/.cmdstanpy as deprecated

---

.readthedocs.yml
docsrc/conf.py

This was a regression when changing config format to v2. In the past, RTD always built a PDF and Epub alongside the html. I don't know if many people knew/used it, but I feel like we should at least maintain the option of a downloadable manual. I don't think it's high enough priority to require a doc rebuild though.

Add pdf build to readthedocs

---

cmdstanpy/install_cmdstan.py

* This PR doesn't change any functionality.
* I think we could split the `clean-all`, `build`, and `test compile` steps of the `install_version` function into different functions. My main use case is to re-use the `clean-all` and `build` steps separately in a packaging pipeline.
Let me know what you think!
Cuong Duong (me)
(macOS Big Sur, cmdstan 2.26.1)
I got 4 unit test errors unrelated to these changes (I think). I'll paste them here anyways:
``` …
```

Separate components of install_version function

---

cmdstanpy/__init__.py
cmdstanpy/install_cmdstan.py
cmdstanpy/model.py
test/test_install_cmdstan.py

This adds a `rebuild_cmdstan` function which goes to the current cmdstan_path and runs make clean and make build using the functions from #451. In theory this should be even better than `install_cmdstan(overwrite=True)` because it allows you to rebuild cmdstan even if it was installed manually or via conda, so long as `cmdstan_path()` can find it.

Add a rebuild_cmdstan function

---

.pylintrc
cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/utils.py
test/test_cxx_installation.py

`utils.install_cmdstan` no longer shells out to install cmdstan, instead it builds up a dictionary of arguments in the same way argparse would and calls the code directly.

Refactor install function to not use a subprocess

---

cmdstanpy/utils.py
test/test_utils.py

This changes `write_stan_json` to turn `Nan` into `"NaN"`, `inf` to `"+inf"`, and `-inf` to `"-inf"` as CmdStan expects. It only calls this as necessary, so it shouldn't be too much less efficient than the prior check which threw an error in these cases.

Serialize inf/nan to json

---

.github/workflows/main.yml
cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
setup.py

This PR fixes `setup.py` console script entrypoints as discussed in #499.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Imperial College London

Fix install entrypoints (fixes #499).

---

.github/workflows/main.yml

This edits our main workflow to allow you to run it manually and specify a cmdstan version. Hopefully it is useful for things like https://github.com/stan-dev/cmdstan/issues/1061

Update workflow to allow manual runs on different CmdStan versions

---

.github/workflows/main.yml
cmdstanpy/utils.py
test/test_utils.py

Addresses #506.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): myself

Restore cwd after do_command error WIP

---

cmdstanpy/stanfit/mcmc.py

Avoid loading the generated samples multiple times if multiple variables are accessed via `stan_variable('var_name')` which can take significant amount of time for large sample files. Unfortunately I had problems to run the unit test. Would somebody else run them, please?
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of Stuttgart

assemble draws and generated quantities only once

---

.github/workflows/main.yml
.pre-commit-config.yaml
cmdstanpy/cmdstan_args.py
cmdstanpy/stanfit/mcmc.py
cmdstanpy/stanfit/mle.py
cmdstanpy/stanfit/vb.py
cmdstanpy/utils.py
pyproject.toml
requirements-test.txt
setup.py

Closes #491. Python 3.6 reached end of life over the holidays. We can go back to only testing 4 versions, and if we want we can start using features of 3.7+ such as the `capture_output` flag to `subprocess.run`

Remove Python 3.6 from test set

---

cmdstanpy/utils.py

Closes #522. Avoids the use of `basicConfig`, which changes the root logger level. Behavior for cmdstanpy on its own should be unchanged.

Avoid changing root logger level

---

.github/workflows/main.yml

The condition in the Github Actions file was backwards, so it was impossible to actually run with a custom version. Wanted to fix this before the RC next week

Fix custom version in GHA runs

---

requirements.txt

After #511 we can require a more recent version of numpy

Update pinned numpy version

---

cmdstanpy/model.py
test/conftest.py
test/test_sample.py

This fixes a few issues discovered while testing the 2.29 release candidate:
1. The `fixed_param` changes are not in 2.29, which we were assuming they would be
2. src_info() would fail if the model had any warnings, since `do_command` would combine the stderr and stdout streams. This bug exists even without 2.29, it just wasn't uncovered until the new warnings were added to stanc
3. I patched around `atexit` in the tests to handle the intermitten issues with logging and pytest
4. The text of the "diagnose" command changed (it outputs more digits of permission)
By submitting this pull request, the copyright holder is agreeing to license …

Fix tests and src_info for 2.29

---

cmdstanpy/compiler_opts.py
test/test_model.py

add test for all compile options
Accidentally numbered the 'O' options as ```O1``` and ```O2``` rather than ```O0``` and ```O1``` .
Fixed this and extended tests to try each optimization during compile. 
J. Michael Burgess

fix numbering of compiler options

---

cmdstanpy/stanfit/mcmc.py
cmdstanpy/stanfit/mle.py
cmdstanpy/stanfit/vb.py
cmdstanpy/utils.py
test/data/named_output.stan
test/test_generate_quantities.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

For all the fit objects, `fit.foo` is now a synonym for `fit.stan_variable("foo")`. This follows the default Python behavior where built-in attributes and functions are resolved before this, so if you name a variable `draws`, then `foo.draws` will still bind the function, forcing you to use `foo.stan_variable("draws")`

Support `.` syntax for Stan variable access

---

cmdstanpy/stanfit/mcmc.py

Closes #550 by cleaning up the `summary` method and changing it's default sig-fig value to `6` 

Update default precision for summary()

---

cmdstanpy/model.py

Closes #545. Both `sample` and `generate_quantities` will now detect any errors in the console log even if the return code is not set to a nonzero value. Exceptions in the generated quantities block do not change the return code of the model executable - see https://github.com/stan-dev/cmdstan/issues/1082

Detect failures in generated quantities

---

cmdstanpy/stanfit/runset.py
test/data/normal-rng.stan
test/test_sample.py

Closes #568. When no output directory is specified, each runset creates its own subfolder in the `_TMPDIR` directory to avoid name clashes. This has also affected fbprophet.
When the output directory _is_ specified, name clobbering will still occur - we assume the user knows what is going on in that case.

Make a subdirectory of the temporary directory per-runset

---

cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/utils.py
test/__init__.py
test/test_cxx_installation.py
test/test_utils.py

This is inspired by https://github.com/stan-dev/cmdstanr/issues/605. 
This PR adds a `--interactive` (short `-i`) flag to the `install_cmdstan` script. If this is set, it drops the user into a series of prompts for each setting which would normally be a command line flag. This lets us elaborate on the questions, provide defaults, etc.
For now, this only implements the existing settings: version, installation directory, verbose/progress bars, number of cores to use for building, and on Windows whether they want RTools. This also needs doc, but I wanted to get it up for discussion alongside #578 
With the framework in place, we can later extend to more complicated settings like pre-setting some `make/local` variables.
Example prompt:
```shell
$ install_cmdstan -i
Which version would you …
```

Add an interactive option to `install_cmdstan`

---

.github/workflows/main.yml
cmdstanpy/install_cmdstan.py
cmdstanpy/utils.py
test/test_utils.py

Closes #585. Improves error messaging when cmdstan path is pointed toward a folder with no binaries, and changes our CI to use the code path on linux and mac.
Now:
Linux, mac: uses `python -c "import cmdstanpy; cmdstanpy.install_cmdstan()"`
Windows: uses `python -m cmdstanpy.install_cmdstan`
Hopefully this will catch regressions like this in the future

Fix location setting after install_cmdstan()

---

docsrc/users-guide.rst
docsrc/users-guide/hello_world.rst
docsrc/users-guide/outputs.rst

Closes #594. This adds a new page to the doc called "Controlling Outputs". I moved a lot of the CSV file specific stuff there from the Hello World page and added a section explaining the `logging` module vis-a-vis cmdstanpy

Add documentation page on csv files and logging

---

.github/workflows/main.yml
cmdstanpy/install_cmdstan.py
cmdstanpy/utils/cmdstan.py
docsrc/installation.rst

Closes #615. This PR changes the URL used in `install_cmdstan` to try to use the specific non-x86 linux binaries when applicable. It does its best to determine this automatically based on the value of `platform.machine()`. 
Users can specify an environment variable, `CMDSTAN_ARCH`, to override the default choice

Download correct CmdStan tarball on non-x86 linux

---

.github/ISSUE_TEMPLATE.md
cmdstanpy/model.py
test/test_model.py

Closes #618. This change makes it so we are never in a situation where compilation failed but nothing gets printed. It does that by trying to be less clever about errors, it just unconditionally prints the console if `make` failed.
This also fixes something which has bugged me for a while, which is that `compile` never threw its own error, but rather this error was thrown after the fact in the constructor. This was really confusing, especially if you initialized the model with `compile=False` and called `compile()` later.
- Code: …

Simplify error reporting during compile()

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
test/test_cmdstan_args.py
test/test_optimize.py

Closes #617. The algorithm specific arguments such as `tol_grad` only parse if you explicitly set `algorithm=` to a valid algorithm. Previously we were checking that it was _not_ set to an invalid choice, now we are checking that it _is_ set to a valid one.
Additionally, we now print the command that failed if optimization fails. We already do this for sampling etc.

Tighten optimization argument requirements, print command

---

cmdstanpy/model.py
cmdstanpy/stanfit/runset.py
test/data/timeout.stan
test/test_generate_quantities.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

This PR adds a `timeout` parameter to `optimize`, `sample`, `generate_quantities`, and `variational` including unit tests. I was running hyperparameter sweeps for a model and some configurations took much longer than others. Setting a timeout means that "bad" configurations can be aborted if they take too long.
I used a `threading.Timer` to terminate the cmdstan subprocess. Checking the elapsed time in `_run_cmdstan` didn't work because the `readline` call blocks until the next line of `stdout` becomes available (which can take a while if the model is sampling inefficiently).
Harvard University
By submitting this pull request, the copyright holder is …

Add timeout parameter.

---

.pre-commit-config.yaml
.pylintrc
cmdstanpy/model.py
cmdstanpy/utils/__init__.py
cmdstanpy/utils/json.py
cmdstanpy/utils/stancsv.py
docsrc/users-guide/examples/Run Generated Quantities.ipynb
requirements-test.txt
requirements.txt
test/data/data-test.stan
test/test_sample.py
test/test_utils.py

We implemented our json encoding based on the spec given in the Cmdstan Users Guide, which was incorrect. In particular, the value `"inf"` does not parse. The default values Python serializes these to _does_, so we should just leave it as it is.
I also removed ujson as part of this fix. ujson implemented differing behavior from Python for infinity which meant round-tripping values was not possible. This was first noted in April of 2013, and did not get fixed until ujson 5.5.0 released last week. So, the options were either pin >=5.5.0, or just remove it. 
By submitting this pull request, the copyright holder is agreeing to license the …

Fix json encoding of NaN/infinity

---

cmdstanpy/model.py
test/data/add_one_model.stan
test/data/include-path/add_one_function.stan
test/test_model.py

This PR addresses #614 by running up-to-date checks recursively on included files.

Recursive up-to-date checks (ref #614).

---

.pre-commit-config.yaml
cmdstanpy/stanfit/mle.py

The `optimized_params_dict` method generates its dictionary by iterating over a numpy array, which produces a numpy item type instead of the base python type; however, the method was annotated with `Dict[str, float]`.  This was creating type checking errors downstream. Here, the annotation is changed to `Dict[str, np.float64]`
In addition, the various linters were upgraded to get pre-commit to run, since they weren't working on newer python versions.
- Stan Developers and their Assignees
- Code: BSD 3-clause …

more accurate type hints

---

cmdstanpy/stanfit/gq.py
cmdstanpy/stanfit/mcmc.py
test/test_generate_quantities.py
test/test_optimize.py
test/test_sample.py
test/test_variational.py

- add a call to `_assemble_draws` to the `__getstate__` magic function such that samples are included when a fit object is serialized with `pickle` or `dill`.
- remove checks before calling `_assemble_draws` because the function already performs this check internally.

Add serialization of samples.

---

.github/workflows/main.yml

This adds the newly released Python 3.11 to the CI we run. Python 3.7 can be removed in 7 months (https://endoflife.date/python)

Add Python 3.11 to CI

---

cmdstanpy/model.py
test/test_model.py

This PR changes `src_info` from logging errors at `DEBUG` level to raising errors that can be caught by client code. It makes `cmdstanpy` somewhat more defensive but existing tests pass without error (at least on my machine). This PR is motivated by [discussion with @WardBrian](https://github.com/stan-dev/cmdstanpy/pull/627#issuecomment-1285714564) in #627.

Raise errors when `src_info` subprocess fails.

---

docsrc/installation.rst

- ~Run unit tests~
There is one extra `/` in the github install command so pip tries to install the branch `/develop` instead of `develop`
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): myself

fix install command for github install

---

cmdstanpy/model.py
cmdstanpy/stanfit/gq.py
docsrc/changes.rst
docsrc/community.rst
docsrc/users-guide/examples/Run Generated Quantities.ipynb
docsrc/users-guide/workflow.rst

Closes #645. I'd like to merge this shortly before running the release script for `1.1.0-rc1`.
@mitzimorris I propose merging this and running the release candidate next Tuesday, after the holiday

Update documentation for 1.1.0

---

.github/workflows/main.yml

The `get-cmdstan-version` GitHub Action job fails silently if the version cannot be determined (cf. [this failed build](https://github.com/stan-dev/cmdstanpy/actions/runs/4316294220/jobs/7532626198)). This PR ensures the workflow fails if the version cannot be determined.

Fail GitHub action workflow if the cmdstan version cannot be determined.

---

cmdstanpy/utils/cmdstan.py

Correctly fetch ppc64el CmdStan

---

cmdstanpy/install_cmdstan.py

Closes #672. This now only checks if the requested version is available _after_ determining that the requested version is not already installed (e.g., right before we would try to download it).

Only check version URL after determining if it was already installed

---

.github/workflows/main.yml
cmdstanpy/model.py
cmdstanpy/utils/filesystem.py
test/data/path~with~tilde/bernoulli_path_with_tilde.stan
test/test_model.py
test/test_sample.py
test/test_utils.py

Apple uses tildes in some paths for files that are synced through iCloud (see [here](https://apple.stackexchange.com/q/280338/102603), for example). It's of course a somewhat questionable choice. This PR allows models in these iCloud folders to be compiled and used.

Handle tilde `~` in model paths.

---

docsrc/api.rst
docsrc/index.rst
docsrc/installation.rst
docsrc/users-guide/examples/Run Generated Quantities.ipynb
docsrc/users-guide/examples/VI as Sampler Inits.ipynb
docsrc/users-guide/overview.rst

Doc: spelling fixes

---

.github/workflows/main.yml
cmdstanpy/install_cmdstan.py
cmdstanpy/utils/cmdstan.py

Allows usage like `install_cmdstan --version=git:develop`. Note: released versions will still always be selected over git versions by the `cmdstan_path()` function unless manually set or only one version exists.
This is primarily for our own CI

Allow git:TAG as a version in install_cmdstan

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit/__init__.py
cmdstanpy/stanfit/gq.py
cmdstanpy/stanfit/laplace.py
cmdstanpy/stanfit/mcmc.py
cmdstanpy/utils/data_munging.py
cmdstanpy/utils/stancsv.py
test/test_laplace.py
test/test_log_prob.py

Currently WIP
Closes #649
See https://github.com/stan-dev/cmdstanr/issues/760#issuecomment-1516609693 for details

[Stan 2.32] Laplace method and other changes

---

cmdstanpy/stanfit/gq.py
cmdstanpy/stanfit/mcmc.py
test/test_generate_quantities.py
test/test_sample.py

Add "chain__", "iter__", and "draw__" columns to draws_pd

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
cmdstanpy/stanfit/runset.py
cmdstanpy/utils/__init__.py
cmdstanpy/utils/filesystem.py
test/test_sample.py
test/test_utils.py

This closes #687 and #362, and cleans up a lot of the temp file code we currently have.
The actual test is guarded behind a version test due to [this cmdstan bug](https://github.com/stan-dev/cmdstan/pull/1191), but locally I have confirmed the fix works

Allow multiple dicts in inits, fix multichain

---

cmdstanpy/compiler_opts.py
test/test_model.py

Including `include-paths` in the `stanc_options` passed to compile currently breaks compilation if `include-paths` is a list of paths rather than a string with comma-separated paths. This PR adds conditional handling based on the type.
Follow-up question: Calling `compile` extends `self._compiler_options` such that the call changes the state of `CmdStanModel` in addition to compiling the model. Is that intended? My gut feeling would've been that passing in `stanc_options` would only affect this one call but not future ones.
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following …

Fix handling of `include-paths` in compiler options.

---

cmdstanpy/model.py
test/test_log_prob.py

Add `sig_figs` option to the `log_prob` method, e.g., for checking manual gradients to higher precision. I have added tests that compare with a literal string of the expected digits because estimating the number of digits from a float can be fiddly.

Add `sig_figs` option for `log_prob`.

---

cmdstanpy/__init__.py
cmdstanpy/compilation.py
cmdstanpy/model.py
test/test_compiler_opts.py
test/test_model.py

The pre-2.0 part of #695 
This moves the compilation code outside the model class and issues deprecation warnings for cases we'd like to disallow in 2.0, namely the use of a CmdStanModel without an executable at all.
I think if we get this in, I can update #691, and then we can release 1.2.0 
Simons Foundation.

Move compilation code, deprecate constructing a model without ever compiling

---

docsrc/users-guide/workflow.rst

**Overview:** Two minor documentation changes on the CmdStanPy workflow documentation page
- remove period from middle of sentence
- make link formatting consistent
for the optimization inference algorithm.
**Details:** More specifically, the documentation for every Stan inference algorithm on this documentation page, follows the form of "Stan's *some algorithm*", with a link to the algorithm itself.
However, the optimization algorithm is the only type of inference algorithm that includes the word "Stan" as part of the link. No other inference algorithm does this.
By submitting this pull request, the copyright holder is agreeing to …

Fix minor doc typos

---

cmdstanpy/stanfit/mcmc.py
cmdstanpy/utils/stancsv.py

In Stan 2.34, the unit_e metric has an extra line in the CSV file:
```
```
which we need to skip over

Stan 2.34: Fix parsing of unit_e output files

---

cmdstanpy/stanfit/gq.py
cmdstanpy/stanfit/mcmc.py
test/test_generate_quantities.py
test/test_sample.py

Closes #717. This makes it so the columns added in #677 (e.g. `chain__`) can be filtered by using the `vars` argument, the same way e.g. `lp__` can.

Allow the 'vars' argument to draws_pd to filter new columns

---

cmdstanpy/cmdstan_args.py
test/test_cmdstan_args.py
test/test_sample.py

And, prevent adapting with no warmup
Closes #730 

Allow warmup iterations when not adapting

---

cmdstanpy/__init__.py
cmdstanpy/compilation.py
cmdstanpy/model.py
docsrc/api.rst

Closes #739 by providing a function outside the model class which allows for calling the formatter.

Extract format functionality from Model class

---

cmdstanpy/cmdstan_args.py
cmdstanpy/model.py
test/test_pathfinder.py
test/test_sample.py

Closes #738 by adding a keyword argument `num_threads`. This checks that the model was compiled with `STAN_THREADS` defined and if so, sets the environment variable `STAN_NUM_THREADS` to the desired value.
This also fixes a small oversight pointed out on the forums: https://discourse.mc-stan.org/t/pathfinder-does-not-accept-multiple-inits/34580/

Add a num_threads helper argument to pathfinder()

---

cmdstanpy/stanfit/pathfinder.py
cmdstanpy/utils/stancsv.py
test/test_optimize.py

Two changes in cmdstan: 
1. The CSV files now report booleans as `true` or `false`
2. RNG updates invalidated old seeds, which changed some tests

Fix tests for new cmdstan

---

cmdstanpy/install_cmdstan.py
cmdstanpy/install_cxx_toolchain.py
cmdstanpy/stanfit/runset.py
cmdstanpy/utils/stancsv.py
test/test_sample.py

Closes #750 - profile_files is now like stdout_files where there is only one of them when there is only one process being run.
Note: I am not convinced cmdstanpy's API here makes any sense. The profile file is _not_ like the diagnostic file where it is only saved if requested, but rather it is saved _if the model in question uses the profiling feature at all_. The default value is `'profile.csv'`, not `''`

Fix profile file output when running multiple chains in one process

---

cmdstanpy/utils/stancsv.py
docsrc/changes.rst
test/test_sample.py

Scan string true and false in scan_config

---

cmdstanpy/model.py
test/test_model.py

This PR adds the `diagnose` method to `CmdStanModel` which can be used to verify gradients, e.g., explicit gradients for custom functions implemented in C++. Documentation is based on the [equivalent `cmdstanr` function](https://mc-stan.org/cmdstanr/reference/model-method-diagnose.html) and other methods, such as `CmdStanModel.variational`.

Add `diagnose` method to `CmdStanModel`.
